### ISSUE TITLE
Standardized cover page for each chapter?

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook#29]
I like what @jdwilkins75 did with including a link to his Twitter so people can follow him. Same with the online presence added by @abrignoni in his section. I also like how @jijames and I have images on the first page of our respective chapters. I feel like we should have some sort of standardized first page for each chapter, especially given that this book is not written by one person. Each chapter is its own entity from the other parts of the book, if that makes sense. 

Loosely thinking something like this

```
Chapter Name Goes Here

[text](image_filename.jpg)

By: FirstName LastName

**something should go here for Twitter or whatever preferred social media presence**
```

Anything more? Anything less? Anything different? Let me know your thoughts!

**Comment by stark4n6** [comment]
Seems good with me, I do think we should include the chapter number alongside the title.

Chapter XX
<Insert title>

**Comment by AndrewRathbun** [comment]
> Seems good with me, I do think we should include the chapter number alongside the title.
> 
> Chapter XX
> <Insert title>

I thought so too but when I viewed it in a PDF and in the table of contents, it would be duplicative a bit. I'll post snips of examples here in a bit.

**Comment by AndrewRathbun** [comment]
Alright, let's see what we think about these examples:

![image](https://user-images.githubusercontent.com/36825567/166261236-c1a0c24f-3921-4181-a34c-ceacff6c2c75.png)


```
# Chapter # - Chapter Title

## Subheadings goes here
## Subheadings goes here
## Subheadings goes here
## Subheadings goes here
## Subheadings goes here
## Subheadings goes here

Content goes here. Remember, only what is put here is parsed by Leanpub to generate the PDF/MOBI/EPUB files.
```



```
# Chapter number goes here

## Chapter Title

### Subheadings goes here
### Subheadings goes here
### Subheadings goes here
### Subheadings goes here
### Subheadings goes here
### Subheadings goes here
### Subheadings goes here

Content goes here. Remember, only what is put here is parsed by Leanpub to generate the PDF/MOBI/EPUB files.
```

ignore the bad grammar in the above examples, I whipped them up very hastily, but it gets the point across. Thoughts on which one (or option C) that we should use?

**Comment by jijames** [comment]
Chapter # - Chapter Title... PLEASE

**Comment by stark4n6** [comment]
Yes, agreed with Josh

Chapter # - Chapter Title looks the cleanest

**Comment by AndrewRathbun** [comment]
I agree with all the above, as well. Unless a few others disagree, then we'll roll with this. I'll make the changes now to set the stage for others.

**Comment by AndrewRathbun** [comment]
https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/commit/c651da09ab69d0c013c929449e926bee86641996 and https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/commit/0d5342e071cbff97fbe1ebc27f777c9c96122b20 are live now

**Comment by AndrewRathbun** [comment]
New preview files added: https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/commit/d300c1a9803a7d39aa2ad733d3fa735c27fa4c38

Will close this Issue for now. Thanks all 👍
