### ISSUE TITLE
Title of Book (FINAL ROUND OF VOTING IS LIVE)

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook#4]
CrowdsourcedDFIRBook is not a great title :) Anyone have any ideas?

EDIT: 5/26/2022

Go here for a link to first round of voting: https://github.com/Digital-Forensics-Discord-Server/CrowdsourcedDFIRBook/issues/4#issuecomment-1138678272

**Comment by ApexPredator-InfoSec** [comment]
Spitballing ideas for book title, what about that old Sierra game, originally called Hero's Quest until trademarks made it change to Quest for Glory: So you want to be a Hero. The player is a recent graduate of the Famous Adventurer's Correspondence School and the adventurers handbook in it is called "So You Want To Be A Hero." Could call it "So You Want To Be An Incident Responder." Or we could come up with something even more nerdy/obscure. I find the more esoteric the better.

**Comment by AndrewRathbun** [comment]
I'm all for nerdy because, let's be real, we're all nerds. I would shy away from using Incident Responder though because that's not generalized enough to encompass topics that have been committed thus far. Mostly referring to the 2 (and counting) mobile chapters which frankly doesn't play much a role in Incident Response, in my experience. 

I like the title Crowdsourced DFIR Book but it's a bit too....caveman, but I like the self-descriptive nature of the title. It would be awesome to think of a title that is self-apparent that the book is a patchwork collaborative effort, if that makes sense? If we never land on one that meets this criteria, it's fine, but if there's something out there that could check that box, I personally think that would be one worth considering.

**Comment by mdawsonuk** [comment]
I'd like a title that focuses it around collective experiences and knowledge... something along the vein of "tales from the DFIR trenches" I think works well... 

The title is going to be the hardest part to get right by far

**Comment by abrignoni** [comment]
DFIR CO-OP: Practical knowledge by and for practitioners
Getting there together: Practical DFIR knowledge for all
DFIR Crowd Wisdom Volume 1
DFIR Anthology: Random bits

**Comment by AndrewRathbun** [comment]
I really like ` DFIR Insights: From the community, for the community`. I think that's on to something. Just my thoughts so far. Keep spitballing, all!

**Comment by ApexPredator-InfoSec** [comment]
I was thinking earlier today along the lines of the "tales from the DFIR trenches" theme as well. maybe something like:
Adventures in DFIR: A Crowdsourced eBook
Tales From the DFIR Bonfire
The Hitchhikers Guide to DFIR: Experiences From Beginners and Experts

**Comment by AndrewRathbun** [comment]
> I was thinking earlier today along the lines of the "tales from the DFIR trenches" theme as well. maybe something like:
> Adventures in DFIR: A Crowdsourced eBook
> Tales From the DFIR Bonfire
> The Hitchhikers Guide to DFIR: Experiences From Beginners and Experts

Ooh I like the bonfire one too. The Discord Server is pretty much like a water cooler/bonfire so that fits the source of where we gathered initially to collaborate on this.

**Comment by AndrewRathbun** [comment]
I also think we can have a subtitle or description on the cover page, so keep that in mind.

**Comment by Br3W7h1S** [comment]
I am loving this book idea, guys! 😁

To throw one into the mix, how about, "DFIR Community Book of Knowledge: Volume 1"

In many industries you have the formally recognised "Book of Knowledge" (For example, I remember studying the DMBOK during my MSc, which is the "Data Management Book of Knowledge", and most other industries have them.  This could be the "community" equivalent? (if you see what I mean) 😃

**Comment by abrignoni** [comment]
> I am loving this book idea, guys! 😁
> 
> To throw one into the mix, how about, "DFIR Community Book of Knowledge: Volume 1"
> 
> In many industries you have the formally recognised "Book of Knowledge" (For example, I remember studying the DMBOK during my MSc, which is the "Data Management Book of Knowledge", and most other industries have them.  This could be the "community" equivalent? (if you see what I mean) 😃

I like this suggestion.

**Comment by AndrewRathbun** [comment]
> I am loving this book idea, guys! 😁
> 
> To throw one into the mix, how about, "DFIR Community Book of Knowledge: Volume 1"
> 
> In many industries you have the formally recognised "Book of Knowledge" (For example, I remember studying the DMBOK during my MSc, which is the "Data Management Book of Knowledge", and most other industries have them.  This could be the "community" equivalent? (if you see what I mean) 😃

I like this too. Sounds official, leaves it open for a sequel, is self descriptive, etc. I think this is a top candidate. Thanks for the suggestion Phil!

**Comment by dwmetz** [comment]
D B O K (DFIR Book of Knowledge) or DFIRBOK?

**Comment by ApexPredator-InfoSec** [comment]
I think DFIRBOK would work better than DBOK. DFIRBOK also sounds like some type of ultra mega chicken that we must slay or tame before continuing our DFIR quest so that's cool.

**Comment by Whee30** [comment]
how about the answer for every digital forensics question out there? 
"It depends...
a DFIR collaboration"

happy to be along for the ride and help where I can

**Comment by Br3W7h1S** [comment]
> > I am loving this book idea, guys! 😁
> > To throw one into the mix, how about, "DFIR Community Book of Knowledge: Volume 1"
> > In many industries you have the formally recognised "Book of Knowledge" (For example, I remember studying the DMBOK during my MSc, which is the "Data Management Book of Knowledge", and most other industries have them.  This could be the "community" equivalent? (if you see what I mean) 😃
> 
> I like this too. Sounds official, leaves it open for a sequel, is self descriptive, etc. I think this is a top candidate. Thanks for the suggestion Phil!

Thanks guys!  Really glad you like it 😁

**Comment by dsplice** [comment]
How about, DFIR for the Masses, from the Masses?

**Comment by digitalsleuth** [comment]
I'll throw in a couple here:
`Crowd Sourced: An OSINT approach to Digital Forensics` (OSINT being our collective Open-Sourced intelligence ;)
or
`Crowd Sourced: An Open Source approach to Digital Forensics`

**Comment by brootware** [comment]
> I really like ` DFIR Insights: From the community, for the community`. I think that's on to something. Just my thoughts so far. Keep spitballing, all!

This one sounds great amongst all the other wonderful titles!

**Comment by Br3W7h1S** [comment]
> D B O K (DFIR Book of Knowledge) or DFIRBOK?

I think DCBOK (DFIR Community Book of Knowledge) as BoKs are typically officially licensed texts, whereas this would differentiate it as a community edition, while still following a similar format :)

**Comment by Nisarg12** [comment]
Some ideas for the title;
> Sleuth Wisdom 101
> Learner's guide to DFIR
> Baby steps to DFIR
> Marshalled Pieces by Forensicators
> How-to CyberForensics
> Defenders Unite: Crowdsourced DFIR Tales
>DFIR for dummies
> ~~We beg to DFIR~~

**Comment by AndrewRathbun** [comment]
https://forms.gle/eZtkh5NZkzdjwaq66

To protect the integrity of the voting process, a gmail account is required at the time of voting. Let me know if I've missed any suggestions. Let's get this one under way and then in a few weeks we can do a final vote for the top 3. Thoughts on that process?

**Comment by stark4n6** [comment]
@AndrewRathbun the form is radio buttons and not check boxes so you can only choose one entry at this point.

**Comment by AndrewRathbun** [comment]
Try now @stark4n6

**Comment by AndrewRathbun** [comment]
![image](https://user-images.githubusercontent.com/36825567/170615283-1ff302f4-cec8-4a6f-a407-e4cc244ccd96.png)

Results so far :)

**Comment by AndrewRathbun** [comment]
![image](https://user-images.githubusercontent.com/36825567/172070998-4c3aa904-9a11-479c-8d85-90c67780c7cc.png)

5 days left!

**Comment by gh0x0st** [comment]
"It Depends"... I dig it!

**Comment by brootware** [comment]
> ![image](https://user-images.githubusercontent.com/36825567/172070998-4c3aa904-9a11-479c-8d85-90c67780c7cc.png)
> 
> 5 days left!

looks like we got a winner there! :D

**Comment by AndrewRathbun** [comment]
![image](https://user-images.githubusercontent.com/36825567/174166889-f333a946-c0ac-4645-8f87-30f8561ec2d1.png)

**Comment by AndrewRathbun** [comment]
![image](https://user-images.githubusercontent.com/36825567/174672079-9f777ace-a197-4f6a-a577-187807af8278.png)

**Comment by AndrewRathbun** [comment]
![image](https://user-images.githubusercontent.com/36825567/175795460-d19a7e1c-b703-48ac-9702-97a59a36b080.png)

3 more days!

**Comment by AndrewRathbun** [comment]
Last call for voting!
